# Generated by Django 4.2.14 on 2024-12-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movieinfo_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='poster',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
